<template>
  <div class="admin-view with-shared-sidebar">
    <header class="bg-white shadow"><div class="max-w-5xl mx-auto px-4 py-4 flex justify-between items-center"><div class="flex items-center gap-4"><router-link to="/" aria-label="Ir al inicio"><img src="../img/logo_dario.png" alt="Logo institucional" class="h-12 w-12 object-contain drop-shadow-md" /></router-link><router-link to="/dashboard" class="text-gray-600 hover:text-gray-800">← Volver</router-link><h1 class="text-xl font-bold text-red-700">Información institucional</h1></div><div class="flex items-center gap-4"><router-link to="/" class="text-red-700 text-sm">Ver sitio</router-link><button @click="authStore.logout" class="text-red-500 text-sm">Cerrar sesión</button></div></div></header>
    <main class="max-w-5xl mx-auto px-4 py-8"><p class="mb-6 text-gray-600">Esta información aparece en la página pública del colegio.</p><form @submit.prevent="guardar" class="bg-white rounded-lg shadow p-6 space-y-5"><div><label>Nombre del colegio<input v-model="formulario.nombre" required class="input" placeholder="Dario Torregroza Perez" /></label></div><div><label>Descripción<textarea v-model="formulario.descripcion" rows="3" class="input" placeholder="Presentación breve de la institución"></textarea></label></div><div class="grid grid-cols-1 md:grid-cols-2 gap-5"><label>Misión<textarea v-model="formulario.mision" rows="6" class="input" placeholder="Escribe la misión institucional"></textarea></label><label>Visión<textarea v-model="formulario.vision" rows="6" class="input" placeholder="Escribe la visión institucional"></textarea></label></div><div class="grid grid-cols-1 md:grid-cols-2 gap-5"><label>Historia<textarea v-model="formulario.historia" rows="5" class="input"></textarea></label><label>Valores<textarea v-model="formulario.valores" rows="5" class="input" placeholder="Respeto, responsabilidad..."></textarea></label></div><label>Filosofía<textarea v-model="formulario.filosofia" rows="4" class="input"></textarea></label><div class="grid grid-cols-1 md:grid-cols-2 gap-5"><label>Teléfono<input v-model="formulario.telefonoGeneral" class="input" placeholder="(605) 000 0000" /></label><label>Correo institucional<input v-model="formulario.correoGeneral" type="email" class="input" placeholder="info@colegio.edu.co" /></label><label>Sitio web<input v-model="formulario.sitioWeb" type="url" class="input" placeholder="https://..." /></label><label>URL del logo<input v-model="formulario.logoUrl" type="url" class="input" placeholder="https://..." /></label></div><p v-if="mensaje" class="rounded bg-green-100 p-3 text-green-700">{{ mensaje }}</p><p v-if="error" class="rounded bg-red-100 p-3 text-red-700">{{ error }}</p><button :disabled="guardando" class="rounded bg-red-700 px-5 py-3 font-semibold text-white hover:bg-red-800 disabled:opacity-50">{{ guardando ? 'Guardando...' : 'Guardar información' }}</button></form></main>
  </div>
</template>
<script setup>
import { onMounted, ref } from 'vue'
import { useAuthStore } from '../stores/auth'
import api from '../services/api'
const authStore = useAuthStore(); const guardando = ref(false); const mensaje = ref(''); const error = ref(''); const formulario = ref({ nombre: '', descripcion: '', historia: '', mision: '', vision: '', valores: '', filosofia: '', logoUrl: '', telefonoGeneral: '', correoGeneral: '', sitioWeb: '' })
onMounted(async () => { try { const response = await api.get('/api/admin/institucional/info'); if (response.data) formulario.value = { ...formulario.value, ...response.data } } catch (e) { error.value = e.response?.data?.error || 'No se pudo cargar la información' } })
async function guardar() { guardando.value = true; mensaje.value = ''; error.value = ''; try { await api.post('/api/admin/institucional/info/guardar-o-actualizar', formulario.value); mensaje.value = 'Información guardada correctamente.' } catch (e) { error.value = e.response?.data?.error || 'No se pudo guardar la información' } finally { guardando.value = false } }
</script>
<style scoped>
label { display: block; color: #374151; font-size: .875rem; font-weight: 600; }.input { display: block; margin-top: .35rem; width: 100%; border: 1px solid #d1d5db; border-radius: .35rem; padding: .7rem .8rem; font-weight: 400; }.input:focus { outline: none; box-shadow: 0 0 0 2px #b91c1c; }
</style>